In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns

import warnings 
warnings.filterwarnings('ignore')

matplotlib.rcParams['font.family'] = 'Malgun Gothic'  # windows
# matplotlib.rcParams['font.family'] = 'AppleGothic'  # Mac
matplotlib.rcParams['font.size'] = 15  # 글자크기
matplotlib.rcParams['axes.unicode_minus'] = False # 한글 폰트 사용시 마이너스 꺠지지않게 해줌

In [24]:
df = pd.read_csv('train_data(2017-2019).csv', index_col = 0)

In [25]:
df

,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,계약일,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
접수연도,,,,,,,,,,,,,,,,,,,,
2019,11710,송파구,10100,잠실동,1.0,대지,0027,0.0,주공아파트 5단지,20200606,197300,76.50,NaN,1,NaN,NaN,1978.0,아파트,NaN,NaN
2019,11710,송파구,10100,잠실동,1.0,대지,19.0,0.0,잠실엘스,20200111,198000,84.80,NaN,14,NaN,NaN,2008.0,아파트,NaN,NaN
2019,11710,송파구,11100,방이동,1.0,대지,89.0,0.0,올림픽선수기자촌3단지,20191231,162000,83.06,NaN,16,NaN,NaN,1988.0,아파트,NaN,NaN
2019,11500,강서구,10900,방화동,1.0,대지,898.0,0.0,경동팰리스힐,20191231,8500,12.22,0.0,2,NaN,NaN,2014.0,아파트,NaN,NaN
2019,11140,중구,13300,충무로5가,1.0,대지,36.0,2.0,충무로엘크루메크로시티2,20191231,32000,35.57,NaN,8,NaN,NaN,2016.0,아파트,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017,11650,서초구,10800,서초동,1.0,대지,1616,10.0,서초극동스타클래스,20121217,83500,109.97,0.0,2,NaN,NaN,2003.0,아파트,NaN,NaN
2018,11200,성동구,10200,하왕십리동,1.0,대지,258,0.0,청계벽산,20121101,48000,114.46,NaN,18,NaN,NaN,1996.0,아파트,NaN,NaN
2019,11740,강동구,10900,천호동,1.0,대지,528,0.0,삼성,20111005,63000,114.65,NaN,4,NaN,NaN,1997.0,아파트,NaN,NaN
2018,11560,영등포구,11000,여의도동,1.0,대지,54,0.0,진주,20080615,71000,94.31,0.0,7,NaN,NaN,1977.0,아파트,NaN,NaN
2017,11350,노원구,10300,공릉동,1.0,대지,230,0.0,현대아파트,20070329,29900,62.27,0.0,3,NaN,NaN,1984.0,아파트,NaN,NaN

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 270560 entries, 2019 to 2017
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   자치구코드             270560 non-null  int64
 1   자치구명              270560 non-null  object
 2   법정동코드             270560 non-null  int64
 3   법정동명              270560 non-null  object
 4   지번구분              270517 non-null  float64
 5   지번구분명             270517 non-null  object
 6   본번                270517 non-null  object
 7   부번                270517 non-null  float64
 8   건물명               270560 non-null  object
 9   계약일               270560 non-null  int64
 10  물건금액(만원)          270560 non-null  int64
 11  건물면적(㎡)           270560 non-null  float64
 12  토지면적(㎡)           171888 non-null  float64
 13  층                 270560 non-null  int64
 14  권리구분              13484 non-null   object
 15  취소일               0 non-null       float64
 16  건축년도              270560 non-null  float64
 17  건물용도              270560 non-null  object
 18  신고구분              0 non-null       float64
 19  신고한 개업공인중개사 시군구명  0 non-null       float64
dtypes: float64(8), int64(5), object(7)
memory usage: 43.3+ MB

In [30]:
df = df.reset_index()

In [31]:
# 타겟 변수 마지막으로 이동
target_column = '물건금액(만원)'  # 이동시킬 열 이름
df = df[[col for col in df.columns if col != target_column] + [target_column]]

In [32]:
# 필요없는 컬럼삭제
df = df.drop(columns=['자치구코드','법정동코드','지번구분','지번구분명','본번','부번','토지면적(㎡)','권리구분','취소일',
                 '신고구분','신고한 개업공인중개사 시군구명'])

In [33]:
df

,접수연도,자치구명,법정동명,건물명,계약일,건물면적(㎡),층,건축년도,건물용도,물건금액(만원)
0,2019,송파구,잠실동,주공아파트 5단지,20200606,76.50,1,1978.0,아파트,197300
1,2019,송파구,잠실동,잠실엘스,20200111,84.80,14,2008.0,아파트,198000
2,2019,송파구,방이동,올림픽선수기자촌3단지,20191231,83.06,16,1988.0,아파트,162000
3,2019,강서구,방화동,경동팰리스힐,20191231,12.22,2,2014.0,아파트,8500
4,2019,중구,충무로5가,충무로엘크루메크로시티2,20191231,35.57,8,2016.0,아파트,32000
...,...,...,...,...,...,...,...,...,...,...
270555,2017,서초구,서초동,서초극동스타클래스,20121217,109.97,2,2003.0,아파트,83500
270556,2018,성동구,하왕십리동,청계벽산,20121101,114.46,18,1996.0,아파트,48000
270557,2019,강동구,천호동,삼성,20111005,114.65,4,1997.0,아파트,63000
270558,2018,영등포구,여의도동,진주,20080615,94.31,7,1977.0,아파트,71000
270559,2017,노원구,공릉동,현대아파트,20070329,62.27,3,1984.0,아파트,29900